### ISSUE TITLE
Compatibility with pytest-sugar

### ISSUE THREAD

**Issue by bcanyelles** [APSL/pytest-checkipdb#1]
Hi,

I'm testing with your plugin and '_pytest-sugar==0.8.0_' also and raise a pytest-sugar error when your plugin detect an ipdb use but it runs well when there isn't any ipdb. 

So, It seems that your plugin require a `def reportinfo(self)` to guarantee the compatibility with '_pytest-sugar_'.

The error trace when an ipdb is detected using '_pytest-sugar_' is:

> Results (2.72s):
>       35 passed
>        1 failed
> Traceback (most recent call last):
>   File "/home/tomeu/virtualenvs/wdna/bin/pytest", line 11, in <module>
>     sys.exit(main())
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/config.py", line 57, in main
>     return config.hook.pytest_cmdline_main(config=config)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
>     return self._inner_hookexec(hook, methods, kwargs)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
>     res = hook_impl.function(*args)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/main.py", line 127, in pytest_cmdline_main
>     return wrap_session(config, _main)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/main.py", line 122, in wrap_session
>     exitstatus=session.exitstatus)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
>     return self._inner_hookexec(hook, methods, kwargs)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
>     return _wrapped_call(hook_impl.function(*args), self.execute)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
>     wrap_controller.send(call_outcome)
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/_pytest/terminal.py", line 374, in pytest_sessionfinish
>     self.summary_stats()
>   File "/home/tomeu/virtualenvs/wdna/lib/python3.5/site-packages/pytest_sugar.py", line 494, in summary_stats
>     report.location[1] + 1,
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> 
> If you suspect this is an IPython bug, please report it at:
>     https://github.com/ipython/ipython/issues
> or send an email to the mailing list at ipython-dev@scipy.org
> 
> You can print a more detailed traceback right now with "%tb", or use "%debug"
> to interactively debug it.
> 
> Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
>     %config Application.verbose_crash=True
>

**Comment by avallbona** [comment]
Fixed with the last version, 0.3.5.
Thank you.
